import { AppConfig } from "@/types";

export const DEFAULT_CONFIG: AppConfig = {
  stocks: {
    PORTFOLIO: [
      { symbol: "9988.HK", name: "Alibaba", exchange: "HK" },
      { symbol: "0700.HK", name: "Tencent", exchange: "HK" },
      { symbol: "1211.HK", name: "BYD", exchange: "HK" },
      { symbol: "1810.HK", name: "Xiaomi", exchange: "HK" },
      { symbol: "0175.HK", name: "Geely", exchange: "HK" },
      { symbol: "3033.HK", name: "HSTech ETF", exchange: "HK" },
      { symbol: "AAPL", name: "Apple", exchange: "US" },
      { symbol: "MSFT", name: "Microsoft", exchange: "US" },
      { symbol: "GOOGL", name: "Alphabet", exchange: "US" },
      { symbol: "META", name: "Meta", exchange: "US" },
      { symbol: "AMD", name: "AMD", exchange: "US" },
      { symbol: "NVDA", name: "NVIDIA", exchange: "US" },
      { symbol: "TSM", name: "TSMC", exchange: "US" },
      { symbol: "SPY", name: "SPY", exchange: "US" },
      { symbol: "QQQ", name: "QQQ", exchange: "US" },
    ],
  },
  analysis: {
    rsiPeriod: 14,
    macdFast: 12,
    macdSlow: 26,
    macdSignal: 9,
    adxPeriod: 14,
    atrPeriod: 14,
    smaShort: 20,
    smaLong: 50,
    volumePeriod: 20,
    divergenceLookback: 20,
    divergenceThreshold: 0.02,
    scoreHistoryBars: 20,
  },
  signal: {
    entryThreshold: 5.5,
    exitThreshold: 4.0,
    signalConfirmationBars: 3,
    adxThreshold: 28,
    maxHoldingDays: 8,
    trendGateEnabled: true,
    earningsBufferDays: 5,
  },
  backtest: {
    enabled: true,
    initialCapital: 10000,
    lookbackDays: 400,
    commissionRate: 0.001,
    slippageRate: 0.0005,
    use_van_tharp: false,
    signal_mode: "both" as const,
  },
  risk: {
    riskPerTrade: 0.0075,
    atrMultiplier: 2.5,
    trailingAtrMultiplier: 1.25,
    maxPositionSize: 0.25,
    correlationThreshold: 0.7,
    correlationPenalty: 0.5,
  },
  portfolioRisk: {
    killSwitchEnabled: true,
    maxDrawdownThreshold: 0.15,
    coolingPeriodDays: 5,
  },
  monteCarlo: {
    enabled: true,
    runs: 1000,
    blockBootstrap: true,
    dualMethod: true,
    divergenceThreshold: 0.15,
  },
  walkForward: {
    enabled: true,
    trainRatio: 0.7,
    maxDegradation: 0.3,
    reoptimizeDays: 63,
  },
  supertrend: {
    atrPeriod: 10,
    multiplier: 3.0,
    filter_mode: "ema_only" as const,
  },
};
